export const SET_ERRORS = 'SET_ERRORS';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const LOGIN_USER_START = 'LOGIN_USER_START';

export const GET_ALL_SERVICES_START = 'GET_ALL_SERVICES_START';
export const GET_ALL_SERVICES_FINISH = 'GET_ALL_SERVICES_FINISH';
export const CREATE_SERVICE_START = 'CREATE_SERVICE_START';
export const CREATE_SERVICE_FINISH = 'CREATE_SERVICE_FINISH';
export const PROPOSE_TO_SERVICE_START = 'PROPOSE_TO_SERVICE_START';
export const PROPOSE_TO_SERVICE_FINISH = 'PROPOSE_TO_SERVICE_FINISH';
export const GET_SERVICE_START = 'GET_SERVICE_START';
export const GET_SERVICE_FINISH = 'GET_SERVICE_FINISH';

export const GET_CURRENT_PROFILE_START = 'GET_CURRENT_PROFILE_START';
export const GET_CURRENT_PROFILE_FINISH = 'GET_CURRENT_PROFILE_FINISH';
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_FINISH = 'GET_PROFILE_FINISH';
export const MAKE_PROFILE_START = 'MAKE_PROFILE_START';
export const MAKE_PROFILE_FINISH = 'MAKE_PROFILE_FINISH';
