export const SET_ERRORS = 'SET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';

export const GET_ALL_SERVICES_START = 'GET_ALL_SERVICES_START';
export const GET_ALL_SERVICES_FINISH = 'GET_ALL_SERVICES_FINISH';
export const CREATE_SERVICE_START = 'CREATE_SERVICE_START';
export const CREATE_SERVICE_FINISH = 'CREATE_SERVICE_FINISH';
