export const SET_ERRORS = 'SET_ERRORS';

export const LOGIN_USER_START = 'LOGIN_USER_START';
export const LOGIN_USER_WITH_FACEBOOK_START = 'LOGIN_USER_WITH_FACEBOOK_START';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'UNSET_CURRENT_USER';
export const SIGN_UP_START = 'SIGN_UP_START';
export const SIGN_UP_END = 'SIGN_UP_END';

export const GET_ALL_SERVICES_START = 'GET_ALL_SERVICES_START';
export const GET_ALL_SERVICES_FINISH = 'GET_ALL_SERVICES_FINISH';
export const GET_SEARCHED_SERVICES_START = 'GET_SEARCHED_SERVICES_START';
export const GET_SEARCHED_SERVICES_FINISH = 'GET_SEARCHED_SERVICES_FINISH';
export const CREATE_SERVICE_START = 'CREATE_SERVICE_START';
export const CREATE_SERVICE_FINISH = 'CREATE_SERVICE_FINISH';
export const PROPOSE_TO_SERVICE_START = 'PROPOSE_TO_SERVICE_START';
export const PROPOSE_TO_SERVICE_FINISH = 'PROPOSE_TO_SERVICE_FINISH';
export const GET_SERVICE_START = 'GET_SERVICE_START';
export const GET_SERVICE_FINISH = 'GET_SERVICE_FINISH';
export const ACCEPT_SERVICE_PROPOSAL_START = 'ACCEPT_SERVICE_PROPOSAL_START';
export const ACCEPT_SERVICE_PROPOSAL_FINISH = 'ACCEPT_SERVICE_PROPOSAL_FINISH';
export const MARK_SERVICE_DONE_START = 'MARK_SERVICE_DONE_START';
export const MARK_SERVICE_DONE_FINISH = 'MARK_SERVICE_DONE_FINISH';
export const ARCHIVE_SERVICE_START = 'ARCHIVE_SERVICE_START';
export const ARCHIVE_SERVICE_FINISH = 'ARCHIVE_SERVICE_FINISH';
export const ADD_REVIEW_START='ADD_REVIEW_START';
export const ADD_REVIEW_FINISH='ADD_REVIEW_START';

export const GET_CURRENT_PROFILE_START = 'GET_CURRENT_PROFILE_START';
export const GET_CURRENT_PROFILE_FINISH = 'GET_CURRENT_PROFILE_FINISH';
export const GET_PROFILE_START = 'GET_PROFILE_START';
export const GET_PROFILE_FINISH = 'GET_PROFILE_FINISH';
export const MAKE_PROFILE_START = 'MAKE_PROFILE_START';
export const MAKE_PROFILE_FINISH = 'MAKE_PROFILE_FINISH';


// payment action types

export const MAKE_PAYMENT_START = 'MAKE_PAYMENT_START';
export const MAKE_PAYMENT_FINISH = 'MAKE_PAYMENT_FINISH';

// chat action types

export const LOAD_USER_CHATS_START = 'LOAD_USER_CHATS_START';
export const LOAD_USER_CHATS_FINISH = 'LOAD_USER_CHATS_FINISH';


//points action types

export const ADD_POINTS_START='ADD_POINTS_START';
export const ADD_POINTS_FINISH='ADD_POINTS_FINISH';

//comments action types

export const ADD_COMMENT_START='ADD_COMMENT_START';
export const ADD_COMMENT_FINISH='ADD_COMMENT_FINISH';


//Intro action types

export const PASS_INTRO_START='PASS_INTRO_START';
export const PASS_INTRO_FINISH='PASS_INTRO_FINISH';

